services:
  frontend:
    image: nextask-frontend:latest
    container_name: nextask-frontend-app
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      NODE_ENV: ${NODE_ENV}
    ports:
      - "3000:3000"

  mysql:
    image: mysql:8.0
    container_name: nextask-mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  flyway:
    image: flyway/flyway:latest
    container_name: nextask-flyway
    entrypoint: ["/bin/bash", "-c", "flyway -url=\"jdbc:mysql://mysql:3306/${MYSQL_DATABASE}?allowPublicKeyRetrieval=true&useSSL=false\" -user=\"${MYSQL_USER}\" -password=\"${MYSQL_PASSWORD}\" -locations=filesystem:/flyway/sql migrate"]
    depends_on:
      - mysql
    restart: on-failure
    volumes:
      - ./database/migrations:/flyway/sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    environment:
      PMA_HOST: mysql
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  mysql_data:
